final List<Map<String, dynamic>> retailerFields = [
  {'key': 'code', 'label': 'Retailer Code', 'type': 'text', 'required': true},
  {'key': 'name', 'label': 'Retailer Name', 'type': 'text', 'required': true},
  {'key': 'owner_name', 'label': 'Owner Name', 'type': 'text', 'required': true},
  {'key': 'address', 'label': 'Address', 'type': 'text', 'required': true},
  {'key': 'contact', 'label': 'Contact Number', 'type': 'phone', 'required': true},
  {'key': 'email', 'label': 'Email', 'type': 'email', 'required': false},
  {'key': 'gst', 'label': 'GST Number', 'type': 'text', 'required': false},
  {'key': 'pan', 'label': 'PAN Number', 'type': 'text', 'required': false},
  {'key': 'type', 'label': 'Retailer Type', 'type': 'text', 'required': false},
  {'key': 'lat', 'label': 'Latitude', 'type': 'number', 'required': true},
  {'key': 'long', 'label': 'Longitude', 'type': 'number', 'required': true},
  {'key': 'status', 'label': 'Status (1 or 0)', 'type': 'number', 'required': true},
  {'key': 'open_time', 'label': 'Open Time', 'type': 'time', 'required': false},
  {'key': 'close_time', 'label': 'Close Time', 'type': 'time', 'required': false},
  {'key': 'image_path', 'label': 'Image Path', 'type': 'text', 'required': false},
  {'key': 'credit_limit', 'label': 'Credit Limit', 'type': 'number', 'required': false},
  {'key': 'zone', 'label': 'Zone', 'type': 'text', 'required': false},
];